development:
  adapter: postgresql
  encoding: unicode
  database: filrouge_development
  pool: 5
  username: raf
  password: raf
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: filrouge_test
  pool: 5
  username: raf
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: filrouge_production
  pool: 5
  username: raf
  password: